version: '2'
services:
  memcached:
    image: memcached:alpine

  web:
    build:
      context: .
      dockerfile: Dockerfile.test
    ports:
      - "9091:80"
    volumes:
      - ./code:/code
      - ./run_tests.sh:/code/run_tests.sh
      - ./site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - code-network
    links:
      - php

  php:
    build: .
    volumes: 
      - ./code:/code
      - ./log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
    links:
      - mysql
    networks:
      - code-network

  ### uncomment if needed ###
  #redis:
  #  image: redis:alpine

  ### uncomment if needed ###
  #mariadb:
  #  image: mariadb:10.1
  #  working_dir: /code
  #  volumes:
  #    - ./code:/code
  #  environment:
  #    - MYSQL_ROOT_PASSWORD=docker
  #    - MYSQL_DATABASE=db_test
  #    - MYSQL_USER=test
  #    - MYSQL_PASSWORD=test
  #  ports:
  #    - "8083:3306"

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment: 
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=ventum
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
    networks:
      - code-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql:db
    ports:
      - "8082:80"
    environment:
      - PMA_USER=root
      - PMA_PASSWORD=password
      - PHP_UPLOAD_MAX_FILESIZE=100MB
    networks:
      - code-network

networks:
  code-network:
    driver: bridge
